title: Blade
subtitle: ""
description: "a very lightweight, high performance, concise and elegant Web framework"
author: biezhi
language: en
timezone: UTC

url: https://lets-blade.com
root: /
# root: /lets-blade.com/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: blade
deploy:
  type: git
  repository: git@git.coding.net:unique/lets-blade.git
  branch: master

highlight:
  enable: true
  line_number: false

#disqus_shortname: hexojs
google_analytics: UA-107006919-1
#google_adsense: ca-pub-9461880259118621

twitter: biezhii
# weibo: planeart
github: biezhi/blade

skip_render:
  - push.sh
